[package]
name = "volans-codec"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true

[dependencies]
asynchronous-codec = "0.7.0"
prost = "0.14.1"
serde = "1.0.219"
serde_json = "1.0.142"
unsigned-varint = { version = "0.8.0", features = ["futures", "asynchronous_codec"] }
